config/routes.rb
Rails.application.routes.draw do
  
  root 'portfolios#home'
  get '/blog', to: 'portfolios#blog'
  get '/resume', to: 'portfolios#resume'
  get '/basecamp', to: 'portfolios#basecamp'
  resources :projects, only: [:index]
  resources :blogs, only: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    default_scope { order(rank: :asc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = BlogService.new.blogs
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  def home
    @skillz = ["Rails", "Java", "Spring Boot", "ReactJS", "HTML5", "CSS3", "Agile", "Microservices"]
    @projects = Project.all.limit(5)
    @blogs = BlogService.new.blogs[0..1]
  end

  def projects
  end

  def blog
  end

  def resume
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
    def image_resolver(project)
        if [1,3].include? project.id # horizontal image
            image_tag  project.logo_url, class: "horiz-img", alt: project.title
        else
            image_tag  project.logo_url, alt: project.title
        end
    end
end

app/views/blogs/_blog.html.erb
<div class="card">

    <%=image_tag  blog["thumbnail"], alt: blog["title"]%>

    <div class="card-body">
        <h4 class="card-title"><%=blog["title"]%></h4>
        <h5 class="card-subtitle"><%=time_ago_in_words blog["pubDate"].to_datetime%> ago</h5>
        <div class="row flex-spaces child-borders">
            <%= link_to  "Check out", blog["link"], class: "paper-btn", target: "_blank" %>
        </div>
    </div>
</div>

app/views/blogs/index.html.erb
<div class="container hero">
    <div class="row flex-center">
        <div class="text-center">
            <h1><%= title 'Blogs' %></h1>
        </div>
        <%@blogs.each_slice(3) do |blog_row|%>
            <div class="row">
                <%blog_row.each do |blog|%>
                    <div class="col md-4 project-item-card">
                        <%= render partial: 'blogs/blog', locals: {blog: blog} %>
                    </div>
                <%end%>
            </div>
        <%end%>  
    </div>
</div>

app/views/common/_footer.html.erb
<footer class="text-center">
    <p>All rights reserved to <a href="/">Partho Ghosh</a>, 2020</p>
</footer>

app/views/common/_menu.html.erb
<nav class="border fixed split-nav">
  <div class="nav-brand">
    <h3><%= link_to  "Partho.me", root_path %></h3>
  </div>
  <div class="collapsible">
    <input id="collapsible0" type="checkbox" name="collapsible0">
    <button>
    <label for="collapsible0">
        <div class="bar1"></div>
        <div class="bar2"></div>
        <div class="bar3"></div>
      </label>
    </button>
    <div class="collapsible-body">
      <ul class="inline">
        <li><%= link_to  "Home", root_path %></li>
        <li><%= link_to  "Projects", projects_path %></li>
        <li><%= link_to  "Blog", blogs_path %></li>
        <li><%= link_to  "Resume", resume_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/_blog_intro.html.erb
<div id="blog-intro" class="blog-intro margin-top-generic">
    <div class="row flex-center">
        <div class="text-center">
            <h1>Blog</h1>
                <div class="row">
                    <%@blogs.each do |blog|%>
                        <div class="col md-4 project-item-card">
                            <%= render partial: 'blogs/blog', locals: {blog: blog} %>
                        </div>
                    <%end%>
                    <div class="col md-4 project-item-card">
                        <%= link_to  "Show all", blogs_path, class: "paper-btn" %>
                    </div>
                </div>
        </div>
    </div>
</div>

app/views/home/_hero.html.erb
<div class="hero">
    <div class="row flex-center">
        <div class="text-center">
            <h1 class="animate__animated animate__jackInTheBox">Hello World!</h1>
            <h3 class="animate__animated animate__fadeInUp">
                <span>This is <span class="me">Partho Ghosh</span>, changing the world</span>
                <br>
                <span>bit by bit using <span class="skillz"
                                                data-twreplace-charspeed="75" 
                                                data-twreplace-wordspeed="3000"
                                                data-twreplace='<%=@skillz%>'>Ruby</span> </span>
            </h3>
            <a class="paper-btn know-more-margin-top" href="#projects-intro">
                <span>Know more</span>
                <br>
                <span class="down-array">&#8964</span>
            </a>
        </div>
    </div>
</div>

app/views/home/_projects_intro.html.erb
<div id="projects-intro" class="projects-intro margin-top-generic">
    <div class="row flex-center">
        <div class="text-center">
            <h1>Projects</h1>
        </div>
        <%@projects.each_slice(3).with_index do |project_row, index|%>
            <div class="row">
                <%project_row.each do |project|%>
                    <div class="col md-4 project-item-card">
                        <%= render partial: 'projects/project', locals: {project: project} %>
                    </div>
                <%end%>
                <%if index == 1%>
                    <div class="col md-4 project-item-card">
                        <%= link_to  "Show all", projects_path, class: "paper-btn" %>
                    </div>
                <%end%>
            </div>
        <%end%>
    </div>
    <%= render partial: 'projects/project_detail', locals: {projects: @projects} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= display_meta_tags site: 'Partho.me' %>
    <%= display_meta_tags description: 'Hey I am Partho Ghosh and Partho.me is my portfolio website. I am a full stack software engineer. Find out more about me and my work by exploring the site.' %>
    <%= display_meta_tags keywords: 'Partho Ghosh, Developer, Rails Developer, Spring Boot Developer, Software Engineer, Rails, Java, Ruby' %>
    <%= display_meta_tags image_src: 'https://avatars0.githubusercontent.com/u/2009988?s=460&u=86ac34e0ec298d4dcc66707359d883f3c90646fb&v=4' %>
    <%= display_meta_tags og: {title: "Partho Ghosh portfolio", 
                               site_name: "Partho.me", 
                               description: "Hey I am Partho Ghosh and Partho.me is my portfolio website. I am a full stack software engineer. Find out more about me and my work by exploring the site.",
                               image:"https://avatars0.githubusercontent.com/u/2009988?s=460&u=86ac34e0ec298d4dcc66707359d883f3c90646fb&v=4"}%>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://unpkg.com/papercss/dist/paper.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css"/>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'twreplace_min', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <%if Rails.env.production?%>
      <!-- Global site tag (gtag.js) - Google Analytics -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=UA-174171700-1"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-174171700-1');
      </script>
    <%end%>
  </head>

  <body>
    <div class="row site">
        <%= render "common/menu" %>
        <div class="container">
          <%= yield %>
          <%= render "common/footer" %>
        </div>
    </div>
  </body>
</html>

app/views/portfolios/basecamp.html.erb
<div class="container hero">
    <div class="row flex-center">
        <h1><%= title 'Hey Basecamp!'%></h1>
    </div>
    <div class="row">

         <article class="article">
            <h2 class="article-title">Who am I ?</h2>
            <%= image_tag  "https://avatars0.githubusercontent.com/u/2009988?s=460&u=86ac34e0ec298d4dcc66707359d883f3c90646fb&v=4", alt: "me" %>
            <p class="text-lead me">Software Engineer who is passionate about products.</p>
            <p>I am <span class="me">Partho Ghosh</span>. I am a software engineer and I am strongly passionate about products. Atleast this is what I have been doing (for others as well as for myself) from last 9+ years. I have been a polyglot engineer till now writing software in multiple technologies but primarily in <span class="me">Ruby on Rails</span> and <span class="me">Java</span>.
               Besides that I work with plain HTML5, CSS3, AWS and mulitple data stores (Mysql, Mongo, DynamoDB, etc.). I will not call myself a Javascript pro but I can work with it. Whenever I work on any project and make any changes, I would like to consider the impact on end user of the product. I always consider myself as a work-in-progress and focus more on improving the aspects I lack in. Outside programming, I love to play video games (I am a Sony fan and owned all the consoles since PS2), go for long drives, enjoy good food, memes, consume random videos in Youtube and read random articles on internet. Recently, I discovered that I like to cook too as I enjoy the process whenever I get an opportunity to cook.
               One thing I learned about myself is that whatever I do, I give my 100% in that and do it with passion. I live in beautiful city of Bangalore in southern part of India with my family.
            </p>
            <p>Please feel free to explore the rest of the site to know more about me &#x1F642!</p>
         </article>
    </div>
    <div class="row">
        <article class="article">
            <h2 class="article-title">Why Basecamp?</h2>
            <p class="text-lead me">Even before Basecamp, you guys built Ruby on Rails.</p>
            <p>I had a brief opportunity to use Basecamp 3 years back when one of my friends added me as a project team member.  We were trying a new product idea and he had a free trial access for Basecamp.
            Right from get go, Basecamp was super user friendly compared to other Project management tools I have used (JIRA for e.g). But this is not how I came to know of Basecamp. I knew that Basecamp (which was earlier known as 37Signals) was Jason Fried's and DHH's company about whom I came to know via "Rework".</p>
            <p>Back in 2015, my another friend told me about "Rework". I was kind of in a "Startup" mode during that time and was attempting my second initiative. I am not an avid reader but I still gave the book a try and boy I was so glad. I will be honest that I was not able to finish it due to some other commitments, but whatever I went through, it was amazing.
            "<i>Scratch your own itch</i>" is still there with me.</p>
            <p>These are the following reasons why I would like to have a shot and why you should talk to me:</p>
            <ul>
                <li>You guys gave birth to <span class="me">Ruby on Rails</span>, the most productive framework written till to date. The framework almost feels like a great product which literally enables anyone (even non CS people) to easily ramp-up and build things.
                    You guys made a simple product and from my overall experience one thing I have learnt that simple things are hard to create. I want to learn to make simple things from you guys while working with you. </li>
                <li>Its been almost 7 years that I am writing code in Ruby on Rails. But I did not get an opportunity to work with an organization which is using Rails in its fullest glory. I mean the largest project I have worked on using RoR was my own product (<%=link_to "Candeo app", projects_path, target: "_blank"%>).
                I have also seen a lot of resistance from these organizations and found that most of them have a rigid unconvincing stance against this beautiful framework. I want to work in a place where Rails is given its due importance and respect.</li>
                <li>Along with my technical know-how, I will bring on board sheer perseverance, passion, curosity, humbleness, ownership, adaptability and eagerness to learn.</li>
                <li>I have been scaling Rails using queues/background jobs, instance autoscaling (AWS) and caching. Besides these I would like to learn from you guys how to extact more performance out of rails.</li>
            </ul>
         </article>
    </div>
</div>

app/views/portfolios/blog.html.erb
<div class="container hero">
    <div class="row flex-center">
        <h1><%= title 'Blog' %></h1>  
    </div>
    <div class="row flex-center">
         <h2>Coming Soon...</h2>   
    </div>
</div>

app/views/portfolios/home.html.erb
<div class="container">
    <%=render "home/hero"%>
    <%=render partial: 'home/projects_intro', locals: {projects: @projects} %>
    <%=render "home/blog_intro"%>
</div>

app/views/portfolios/resume.html.erb
<div class="container hero">
    <div class="row flex-center">
        <h1><%= title 'Resume' %></h1>  
    </div>
    <div class="row flex-center">
        <%= image_tag  "https://avatars0.githubusercontent.com/u/2009988?s=460&u=86ac34e0ec298d4dcc66707359d883f3c90646fb&v=4", alt: "me" %>
        <p>
            Hey I am <span class="me">Partho Ghosh</span>. I am a Software Engineer who spent about <span class="me">10 years</span> in building production ready software in web (mostly) and mobile domain. I mostly write code in <span class="me">Ruby</span> and <span class="me">Java</span>. My day to day goal is to get continuously better in overall aspects of software engineering like front-end, backend, architecture, scale, alogirhtms, etc. I started my engineering journey with the hopes to become a game developer (and I kind of acheived it when I got hired in Gameloft as game programmer) but then slowly drifted into web/mobile domain. My secret desire is to release my own game some day.
        </p>
    </div>
    <div>
        <div class="row">
            <div class="col md-12">
                <p class="text-center">Contact Me</p>
            </div>
        </div>
        <div class="row">  
                <div class="col md-3"><%=link_to(image_tag("own/gmail.svg", width: 40, class: "margin-left-generic"), "mailto: partho.ghosh24@gmail.com")%></div>
                <div class="col md-3"><%=link_to(image_tag("own/linkedin.svg", width: 40, class: "margin-left-generic"), "https://in.linkedin.com/in/partho-ghosh-21b05835", target:"_blank")%></div>
                <div class="col md-3"><%=link_to(image_tag("own/github.svg", width: 40, class: "margin-left-generic"), "https://github.com/parthoghosh24", target:"_blank")%></div>
                <div class="col md-3"><%=link_to(image_tag("own/angellist.svg", width: 40, class: "margin-left-generic"), "https://angel.co/u/partho-ghosh-758737", target:"_blank")%></div>
        </div>
    </div>    
    <div class="row flex-center">
            <iframe src="https://drive.google.com/file/d/13xB-zL9FGFAAzPxngPed_YVqvSp9qweT/preview" width="640" height="800"></iframe>
    </div>
</div>

app/views/projects/_project.html.erb
<div class="card">
    <div class="project-img-holder">
        <%=image_resolver project%>
    </div>

    <div class="card-body">
        <h4 class="card-title"><%=project.title%></h4>
        <h5 class="card-subtitle"><%=project.subtitle%></h5>
        <p class="card-text"><%=truncate(project.description, length: 115)%></p>
        <div class="row flex-spaces child-borders">
            <label class="paper-btn margin" for="modal-<%=project.id%>">Expand</label>
        </div>
    </div>
</div>

app/views/projects/_project_detail.html.erb
<%projects.each do |project|%>
        <input class="modal-state" id="modal-<%=project.id%>" type="checkbox">
        <div class="modal">
                <label class="modal-bg" for="modal-<%=project.id%>"></label>
                <div class="modal-body">
                    <label class="btn-close" for="modal-<%=project.id%>">X</label>
                    <h4 class="modal-title"><%=project.title%></h4>
                    <h5 class="modal-subtitle"><%=project.subtitle%> - <%=project.role%></h5>
                    <p class="modal-text"><%=project.description%></p>
                    <div class="row">
                        <%project.image_urls.split(",").each do |image_url|%>
                            <%=image_tag image_url, width: 200%>
                        <%end%>
                    </div>
                    <div class="row">
                        <%project.video_urls.split(",").each do |video_url|%>
                            <iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/jt3ePDl_d-0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                        <%end%>
                    </div>
                    <p>
                      <%project.tech_stack.split(",").each do |tech|%>
                            <span class="badge secondary"><%=tech%></span>
                        <%end%>      
                    </p>
                    <%=link_to "Click to Access", project.url, target: "_blank"%>
                    <label for="modal-<%=project.id%>" class="modal-link">Close</label>
                </div>
        </div>
    <%end%>

app/views/projects/index.html.erb
<div class="container hero">
    <div class="row flex-center">
        <div class="text-center">
            <h1><%= title 'Projects' %></h1>
        </div>
        <%@projects.each_slice(3) do |project_row|%>
            <div class="row">
                <%project_row.each do |project|%>
                    <div class="col md-4 project-item-card">
                        <%= render partial: 'projects/project', locals: {project: project} %>
                    </div>
                <%end%>
            </div>
        <%end%>  
    </div>
    <%= render partial: 'projects/project_detail', locals: {projects: @projects} %>
</div>